---
title: "Hypothesis 4"
author: 
date: '`r format(Sys.Date(), "%B %d, %Y")`'
geometry: margin=1in
output: 
  pdf_document:
  number_sections: TRUE
---
  
  
```{r global_options, include=FALSE}
knitr::opts_chunk$set(tidy = TRUE)
knitr::opts_chunk$set(fig.pos = 'H')
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(rmarkdown)
library(knitr)
library(kableExtra)
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(dplyr)
library(geeM)
library(MuMIn)
path_output_data <- Sys.getenv("path_output_data")

# Read in functions for data analysis
source("analysis-utils.R")

# Read in data
dat_baseline_analysis <- read.csv(file.path(path_output_data, "dat_baseline_analysis.csv"), header = TRUE)
dat_screener_analysis <- read.csv(file.path(path_output_data, "dat_screener_analysis.csv"), header = TRUE)
dat_wnw_analysis <- read.csv(file.path(path_output_data, "dat_wnw_analysis.csv"), header = TRUE)

# Center and scale variables
dat_baseline_analysis <- dat_baseline_analysis %>% mutate(across(!c("ParticipantID"), scale))
dat_screener_analysis <- dat_screener_analysis %>% mutate(across(!c("ParticipantID","sex","race","baseline_condition"), scale))
dat_wnw_analysis_0 <- dat_wnw_analysis %>% filter(time==0) %>% mutate(across(!c("ParticipantID","time","survey_timepoint","CASEID","HED","rutgers","condition"), scale))
dat_wnw_analysis_1 <- dat_wnw_analysis %>% filter(time==1) %>% mutate(across(!c("ParticipantID","time","survey_timepoint","CASEID","HED","rutgers","condition"), scale))
dat_wnw_analysis <- rbind(dat_wnw_analysis_0, dat_wnw_analysis_1)
remove(dat_wnw_analysis_0, dat_wnw_analysis_1)

# Merge datasets into one data frame
dat_wnw_analysis <- dat_wnw_analysis %>% arrange(ParticipantID, time)
dat_analysis <- left_join(x = dat_wnw_analysis, y = dat_screener_analysis, by = "ParticipantID")
dat_analysis <- left_join(x = dat_analysis, y = dat_baseline_analysis, by = "ParticipantID")
dat_analysis <- dat_analysis %>% select(colnames(dat_screener_analysis), colnames(dat_baseline_analysis), everything())
```


(H4): The distress-mediated effect of role overload on alcohol misuse weakens over time: It is stronger during the early onboarding phase than the late onboarding phase.


# Model 5

## RAPI

```{r, echo = FALSE, message = FALSE, warning = FALSE}
fit_rutgers_1 <- geem(rutgers ~ sex + race + age 
                      + baseline_rutgers + baseline_social_desirability + baseline_impulsivity + lifestress 
                      + injunctive_workplace_norms + qualitative_role_overload + quantitative_role_overload + DASS
                      + time 
                      + time:qualitative_role_overload + time:quantitative_role_overload
                      + time:DASS, 
                  data = dat_analysis, id = ParticipantID, waves = time, corstr = "exchangeable", family = "poisson")

outfit_rutgers_1 <- FormatGEEOutput(fit_rutgers_1)
N_rutgers_1 <- length(setdiff(unique(dat_analysis$ParticipantID), fit_rutgers_1$dropped))
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
write.csv(outfit_rutgers_1, "prepare-publication-tables/RAPI/injunctive_model_05.csv", row.names=FALSE)
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
outfit_rutgers_1 %>%
  mutate(parameter = gsub("_"," ", .data[["parameter"]])) %>%
  mutate(parameter = gsub(":"," x ", .data[["parameter"]])) %>%
  select(parameter, everything()) %>%
  mutate_all(linebreak) %>%
  kable(booktabs = TRUE, align = c('c','c','c','c'),
        col.names = linebreak(c("Parameter","Estimates","SE","p-value"), align = "c"),
        caption = paste("Outcome: RAPI; N = ", N_rutgers_1, "; QIC = ", round(QIC(fit_rutgers_1), digits = 2), sep=""), escape = FALSE) %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))  
```


## HED


```{r, echo = FALSE, message = FALSE, warning = FALSE}
fit_HED_1 <- geem(HED ~ sex + race + age 
                      + baseline_HED + baseline_social_desirability + baseline_impulsivity + lifestress 
                      + injunctive_workplace_norms + qualitative_role_overload + quantitative_role_overload + DASS
                      + time 
                      + time:qualitative_role_overload + time:quantitative_role_overload
                      + time:DASS, 
                  data = dat_analysis, id = ParticipantID, waves = time, corstr = "exchangeable", family = "poisson")

outfit_HED_1 <- FormatGEEOutput(fit_HED_1)
N_HED_1 <- length(setdiff(unique(dat_analysis$ParticipantID), fit_HED_1$dropped))
```



```{r, echo = FALSE, message = FALSE, warning = FALSE}
write.csv(outfit_HED_1, "prepare-publication-tables/HED/injunctive_model_05.csv", row.names=FALSE)
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
outfit_HED_1 %>%
  mutate(parameter = gsub("_"," ", .data[["parameter"]])) %>%
  mutate(parameter = gsub(":"," x ", .data[["parameter"]])) %>%
  select(parameter, everything()) %>%
  mutate_all(linebreak) %>%
  kable(booktabs = TRUE, align = c('c','c','c','c'),
        col.names = linebreak(c("Parameter","Estimates","SE","p-value"), align = "c"),
        caption = paste("Outcome: Number of past-month heavy drinking days (HED); N = ", N_HED_1, "; QIC = ", round(QIC(fit_HED_1), digits = 2), sep=""), escape = FALSE) %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))  
```


# Model 7

## RAPI

```{r, echo = FALSE, message = FALSE, warning = FALSE}
fit_DASS_1 <- geem(DASS ~ sex + race + age 
                  + baseline_rutgers + baseline_social_desirability + baseline_impulsivity + lifestress
                  + qualitative_role_overload + quantitative_role_overload
                  + time + time:qualitative_role_overload + time:quantitative_role_overload, 
                data = dat_analysis, id = ParticipantID, waves = time, corstr = "exchangeable", family = "gaussian")

outfit_DASS_1 <- FormatGEEOutput(fit_DASS_1)
N_DASS_1 <- length(setdiff(unique(dat_analysis$ParticipantID), fit_DASS_1$dropped))
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
write.csv(outfit_DASS_1, "prepare-publication-tables/DASS/baseline_RAPI_model_07.csv", row.names=FALSE)
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
outfit_DASS_1 %>%
  mutate(parameter = gsub("_"," ", .data[["parameter"]])) %>%
  mutate(parameter = gsub(":"," x ", .data[["parameter"]])) %>%
  select(parameter, everything()) %>%
  mutate_all(linebreak) %>%
  kable(booktabs = TRUE, align = c('c','c','c','c'),
        col.names = linebreak(c("Parameter","Estimates","SE","p-value"), align = "c"),
        caption = paste("Outcome: DASS; N = ", N_DASS_1,  "; QIC = ", round(QIC(fit_DASS_1), digits = 2), sep=""), escape = FALSE) %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))  
```

\newpage


## HED


```{r, echo = FALSE, message = FALSE, warning = FALSE}
fit_DASS_1 <- geem(DASS ~ sex + race + age 
                  + baseline_HED + baseline_social_desirability + baseline_impulsivity + lifestress
                  + qualitative_role_overload + quantitative_role_overload
                  + time + time:qualitative_role_overload + time:quantitative_role_overload, 
                data = dat_analysis, id = ParticipantID, waves = time, corstr = "exchangeable", family = "gaussian")

outfit_DASS_1 <- FormatGEEOutput(fit_DASS_1)
N_DASS_1 <- length(setdiff(unique(dat_analysis$ParticipantID), fit_DASS_1$dropped))
```



```{r, echo = FALSE, message = FALSE, warning = FALSE}
write.csv(outfit_DASS_1, "prepare-publication-tables/DASS/baseline_HED_model_07.csv", row.names=FALSE)
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
outfit_DASS_1 %>%
  mutate(parameter = gsub("_"," ", .data[["parameter"]])) %>%
  mutate(parameter = gsub(":"," x ", .data[["parameter"]])) %>%
  select(parameter, everything()) %>%
  mutate_all(linebreak) %>%
  kable(booktabs = TRUE, align = c('c','c','c','c'),
        col.names = linebreak(c("Parameter","Estimates","SE","p-value"), align = "c"),
        caption = paste("Outcome: DASS; N = ", N_DASS_1,  "; QIC = ", round(QIC(fit_DASS_1), digits = 2), sep=""), escape = FALSE) %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))  
```


\newpage


# Estimate Mediated Effect using Model 5 and Model 7


## RAPI



```{r, echo = FALSE, message = FALSE, warning = FALSE}
# Read in bootstrap estimates
load("analysis/Hypothesis 04/list_models_rutgers.RData")
alpha <- 0.05
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
list_params_rutgers <- list()

for(i in 1:length(list_models_rutgers)){
  curr_model_estimates <- list_models_rutgers[[i]]
  
  tab_DASS <- curr_model_estimates[["est_DASS"]]
  a2 <- tab_DASS[row.names(tab_DASS) == "qualitative_role_overload",][["estimates"]]
  a4 <- tab_DASS[row.names(tab_DASS) == "qualitative_role_overload:time",][["estimates"]]
  a3 <- tab_DASS[row.names(tab_DASS) == "quantitative_role_overload",][["estimates"]]
  a5 <- tab_DASS[row.names(tab_DASS) == "quantitative_role_overload:time",][["estimates"]]

  tab_drinking <- curr_model_estimates[["est_rutgers_injunctive"]]
  b1 <- tab_drinking[row.names(tab_drinking) == "DASS",][["estimates"]]
  b3 <- tab_drinking[row.names(tab_drinking) == "DASS:time",][["estimates"]]
  
  curr_params_rutgers <- data.frame(a2=a2, a4=a4, a3=a3, a5=a5, b1=b1, b3=b3)
  list_params_rutgers <- append(list_params_rutgers, list(curr_params_rutgers))
}
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
bootdat_params_rutgers <- bind_rows(list_params_rutgers) %>%
  # Mediated Effect: Qualitative Role Overload
  mutate(qualitative_role_overload_time_0 = a2*(b1),
         qualitative_role_overload_time_1 = (a2+a4)*(b1+b3)) %>%
  # Mediated Effect: Quantitative Role Overload
  mutate(quantitative_role_overload_time_0 = a3*(b1),
         quantitative_role_overload_time_1 = (a3+a5)*(b1+b3))
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
# Qualitative Role Overload
time_0 <- bootdat_params_rutgers %>%
  summarise(mean_time_0 = mean(qualitative_role_overload_time_0),
            LB_time_0 = quantile(qualitative_role_overload_time_0, probs = alpha/2),
            UB_time_0 = quantile(qualitative_role_overload_time_0, probs = 1-alpha/2))


time_1 <- bootdat_params_rutgers %>%
  summarise(mean_time_1 = mean(qualitative_role_overload_time_1),
            LB_time_1 = quantile(qualitative_role_overload_time_1, probs = alpha/2),
            UB_time_1 = quantile(qualitative_role_overload_time_1, probs = 1-alpha/2))

summary_qualitative_role_overload <- matrix(c(time_0,
                                              time_1),
                                            byrow=TRUE, ncol=3)

summary_qualitative_role_overload <- apply(summary_qualitative_role_overload, 2, unlist)
summary_qualitative_role_overload <- round(summary_qualitative_role_overload, digits=3)
row.names(summary_qualitative_role_overload) <- c("Early Onboarding Phase",
                                                   "Late Onboarding Phase")
colnames(summary_qualitative_role_overload) <- c("Bootstrap Mean","Bootstrap 95%-CI LB","Bootstrap 95%-CI UB")

# Quantitative Role Overload
time_0 <- bootdat_params_rutgers %>%
  summarise(mean_time_0 = mean(quantitative_role_overload_time_0),
            LB_time_0 = quantile(quantitative_role_overload_time_0, probs = alpha/2),
            UB_time_0 = quantile(quantitative_role_overload_time_0, probs = 1-alpha/2))


time_1 <- bootdat_params_rutgers %>%
  summarise(mean_time_1 = mean(quantitative_role_overload_time_1),
            LB_time_1 = quantile(quantitative_role_overload_time_1, probs = alpha/2),
            UB_time_1 = quantile(quantitative_role_overload_time_1, probs = 1-alpha/2))

summary_quantitative_role_overload <- matrix(c(time_0,
                                              time_1),
                                            byrow=TRUE, ncol=3)

summary_quantitative_role_overload <- apply(summary_quantitative_role_overload, 2, unlist)
summary_quantitative_role_overload <- round(summary_quantitative_role_overload, digits=3)
row.names(summary_quantitative_role_overload) <- c("Early Onboarding Phase",
                                                   "Late Onboarding Phase")
colnames(summary_quantitative_role_overload) <- c("Bootstrap Mean","Bootstrap 95%-CI LB","Bootstrap 95%-CI UB")
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
summary_qualitative_role_overload %>%
  kable(booktabs = TRUE, align = c('c','c','c'), caption = "DASS-mediated effect of Qualitative Role Overload; Norms Covariate: Injunctive Norms")  %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))  
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
summary_quantitative_role_overload %>%
  kable(booktabs = TRUE, align = c('c','c','c'), caption = "DASS-mediated effect of Quantitative Role Overload; Norms Covariate: Injunctive Norms")  %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))  
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
write.csv(summary_qualitative_role_overload, "prepare-publication-tables/RAPI/injunctive_qualitative_role_overload_mediated_effect_model_05_and_model_07.csv")
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
write.csv(summary_quantitative_role_overload, "prepare-publication-tables/RAPI/injunctive_quantitative_role_overload_mediated_effect_model_05_and_model_07.csv")
```


## HED


```{r, echo = FALSE, message = FALSE, warning = FALSE}
# Read in bootstrap estimates
load("analysis/Hypothesis 04/list_models_HED.RData")
alpha <- 0.05
```



```{r, echo = FALSE, message = FALSE, warning = FALSE}
list_params_HED <- list()

for(i in 1:length(list_models_HED)){
  curr_model_estimates <- list_models_HED[[i]]
  
  tab_DASS <- curr_model_estimates[["est_DASS"]]
  a2 <- tab_DASS[row.names(tab_DASS) == "qualitative_role_overload",][["estimates"]]
  a4 <- tab_DASS[row.names(tab_DASS) == "qualitative_role_overload:time",][["estimates"]]
  a3 <- tab_DASS[row.names(tab_DASS) == "quantitative_role_overload",][["estimates"]]
  a5 <- tab_DASS[row.names(tab_DASS) == "quantitative_role_overload:time",][["estimates"]]

  tab_drinking <- curr_model_estimates[["est_HED_injunctive"]]
  b1 <- tab_drinking[row.names(tab_drinking) == "DASS",][["estimates"]]
  b3 <- tab_drinking[row.names(tab_drinking) == "DASS:time",][["estimates"]]
  
  curr_params_HED <- data.frame(a2=a2, a4=a4, a3=a3, a5=a5, b1=b1, b3=b3)
  list_params_HED <- append(list_params_HED, list(curr_params_HED))
}
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
bootdat_params_HED <- bind_rows(list_params_HED) %>%
  # Mediated Effect: Qualitative Role Overload
  mutate(qualitative_role_overload_time_0 = a2*(b1),
         qualitative_role_overload_time_1 = (a2+a4)*(b1+b3)) %>%
  # Mediated Effect: Quantitative Role Overload
  mutate(quantitative_role_overload_time_0 = a3*(b1),
         quantitative_role_overload_time_1 = (a3+a5)*(b1+b3))
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
# Qualitative Role Overload
time_0 <- bootdat_params_HED %>%
  summarise(mean_time_0 = mean(qualitative_role_overload_time_0),
            LB_time_0 = quantile(qualitative_role_overload_time_0, probs = alpha/2),
            UB_time_0 = quantile(qualitative_role_overload_time_0, probs = 1-alpha/2))


time_1 <- bootdat_params_HED %>%
  summarise(mean_time_1 = mean(qualitative_role_overload_time_1),
            LB_time_1 = quantile(qualitative_role_overload_time_1, probs = alpha/2),
            UB_time_1 = quantile(qualitative_role_overload_time_1, probs = 1-alpha/2))

summary_qualitative_role_overload <- matrix(c(time_0,
                                              time_1),
                                            byrow=TRUE, ncol=3)

summary_qualitative_role_overload <- apply(summary_qualitative_role_overload, 2, unlist)
summary_qualitative_role_overload <- round(summary_qualitative_role_overload, digits=3)
row.names(summary_qualitative_role_overload) <- c("Early Onboarding Phase",
                                                   "Late Onboarding Phase")
colnames(summary_qualitative_role_overload) <- c("Bootstrap Mean","Bootstrap 95%-CI LB","Bootstrap 95%-CI UB")

# Quantitative Role Overload
time_0 <- bootdat_params_HED %>%
  summarise(mean_time_0 = mean(quantitative_role_overload_time_0),
            LB_time_0 = quantile(quantitative_role_overload_time_0, probs = alpha/2),
            UB_time_0 = quantile(quantitative_role_overload_time_0, probs = 1-alpha/2))


time_1 <- bootdat_params_HED %>%
  summarise(mean_time_1 = mean(quantitative_role_overload_time_1),
            LB_time_1 = quantile(quantitative_role_overload_time_1, probs = alpha/2),
            UB_time_1 = quantile(quantitative_role_overload_time_1, probs = 1-alpha/2))

summary_quantitative_role_overload <- matrix(c(time_0,
                                              time_1),
                                            byrow=TRUE, ncol=3)

summary_quantitative_role_overload <- apply(summary_quantitative_role_overload, 2, unlist)
summary_quantitative_role_overload <- round(summary_quantitative_role_overload, digits=3)
row.names(summary_quantitative_role_overload) <- c("Early Onboarding Phase",
                                                   "Late Onboarding Phase")
colnames(summary_quantitative_role_overload) <- c("Bootstrap Mean","Bootstrap 95%-CI LB","Bootstrap 95%-CI UB")
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
summary_qualitative_role_overload %>%
  kable(booktabs = TRUE, align = c('c','c','c'), caption = "DASS-mediated effect of Qualitative Role Overload; Norms Covariate: Injunctive Norms")  %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))  
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
summary_quantitative_role_overload %>%
  kable(booktabs = TRUE, align = c('c','c','c'), caption = "DASS-mediated effect of Quantitative Role Overload; Norms Covariate: Injunctive Norms")  %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))  
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
write.csv(summary_qualitative_role_overload, "prepare-publication-tables/HED/injunctive_qualitative_role_overload_mediated_effect_model_05_and_model_07.csv")
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
write.csv(summary_quantitative_role_overload, "prepare-publication-tables/HED/injunctive_quantitative_role_overload_mediated_effect_model_05_and_model_07.csv")
```


