---
title: "Additional Analysis: Add two-way and three-way interactions to Model 2"
author: 
date: '`r format(Sys.Date(), "%B %d, %Y")`'
geometry: margin=1in
output: 
  pdf_document:
  number_sections: TRUE
---
  
  
```{r global_options, include=FALSE}
knitr::opts_chunk$set(tidy = TRUE)
knitr::opts_chunk$set(fig.pos = 'H')
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(rmarkdown)
library(knitr)
library(kableExtra)
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(dplyr)
library(geeM)
library(MuMIn)
path_output_data <- Sys.getenv("path_output_data")

# Read in functions for data analysis
source("analysis-utils.R")

# Read in data
dat_baseline_analysis <- read.csv(file.path(path_output_data, "dat_baseline_analysis.csv"), header = TRUE)
dat_screener_analysis <- read.csv(file.path(path_output_data, "dat_screener_analysis.csv"), header = TRUE)
dat_wnw_analysis <- read.csv(file.path(path_output_data, "dat_wnw_analysis.csv"), header = TRUE)

# Center and scale variables
dat_baseline_analysis <- dat_baseline_analysis %>% mutate(across(!c("ParticipantID"), scale))
dat_screener_analysis <- dat_screener_analysis %>% mutate(across(!c("ParticipantID","sex","race","baseline_condition"), scale))
dat_wnw_analysis_0 <- dat_wnw_analysis %>% filter(time==0) %>% mutate(across(!c("ParticipantID","time","survey_timepoint","CASEID","HED","rutgers","condition"), scale))
dat_wnw_analysis_1 <- dat_wnw_analysis %>% filter(time==1) %>% mutate(across(!c("ParticipantID","time","survey_timepoint","CASEID","HED","rutgers","condition"), scale))
dat_wnw_analysis <- rbind(dat_wnw_analysis_0, dat_wnw_analysis_1)
remove(dat_wnw_analysis_0, dat_wnw_analysis_1)

# Merge datasets into one data frame
dat_wnw_analysis <- dat_wnw_analysis %>% arrange(ParticipantID, time)
dat_analysis <- left_join(x = dat_wnw_analysis, y = dat_screener_analysis, by = "ParticipantID")
dat_analysis <- left_join(x = dat_analysis, y = dat_baseline_analysis, by = "ParticipantID")
dat_analysis <- dat_analysis %>% select(colnames(dat_screener_analysis), colnames(dat_baseline_analysis), everything())
```



# Model 2 with two-way interaction between psychological distress and injunctive drinking norms

## RAPI

```{r, echo = FALSE, message = FALSE, warning = FALSE}
fit_rutgers_1 <- geem(rutgers ~ sex + race + age 
                                + baseline_rutgers + baseline_social_desirability + baseline_impulsivity + lifestress 
                                + injunctive_workplace_norms + qualitative_role_overload + quantitative_role_overload + DASS + DASS:injunctive_workplace_norms, 
                  data = dat_analysis, id = ParticipantID, waves = time, corstr = "exchangeable", family = "poisson")

outfit_rutgers_1 <- FormatGEEOutput(fit_rutgers_1)
N_rutgers_1 <- length(setdiff(unique(dat_analysis$ParticipantID), fit_rutgers_1$dropped))
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
outfit_rutgers_1 %>%
  mutate(parameter = gsub("_"," ", .data[["parameter"]])) %>%
  mutate(parameter = gsub(":"," x ", .data[["parameter"]])) %>%
  select(parameter, everything()) %>%
  mutate_all(linebreak) %>%
  kable(booktabs = TRUE, align = c('c','c','c','c'),
        col.names = linebreak(c("Parameter","Estimates","SE","p-value"), align = "c"),
        caption = paste("Outcome: RAPI; N = ", N_rutgers_1, "; QIC = ", round(QIC(fit_rutgers_1), digits = 2), sep=""), escape = FALSE) %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))  
```

\newpage

## HED

```{r, echo = FALSE, message = FALSE, warning = FALSE}
fit_HED_1 <- geem(HED ~ sex + race + age 
                                + baseline_HED + baseline_social_desirability + baseline_impulsivity + lifestress 
                                + injunctive_workplace_norms + qualitative_role_overload + quantitative_role_overload + DASS + DASS:injunctive_workplace_norms, 
                  data = dat_analysis, id = ParticipantID, waves = time, corstr = "exchangeable", family = "poisson")

outfit_HED_1 <- FormatGEEOutput(fit_HED_1)
N_HED_1 <- length(setdiff(unique(dat_analysis$ParticipantID), fit_HED_1$dropped))
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
outfit_HED_1 %>%
  mutate(parameter = gsub("_"," ", .data[["parameter"]])) %>%
  mutate(parameter = gsub(":"," x ", .data[["parameter"]])) %>%
  select(parameter, everything()) %>%
  mutate_all(linebreak) %>%
  kable(booktabs = TRUE, align = c('c','c','c','c'),
        col.names = linebreak(c("Parameter","Estimates","SE","p-value"), align = "c"),
        caption = paste("Outcome: Number of past-month heavy drinking days (HED); N = ", N_HED_1, "; QIC = ", round(QIC(fit_HED_1), digits = 2), sep=""), escape = FALSE) %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))  
```

\newpage

# Model 2 with three-way interaction between psychological distress, injunctive drinking norms, and time

## RAPI

```{r, echo = FALSE, message = FALSE, warning = FALSE}
fit_rutgers_1 <- geem(rutgers ~ sex + race + age 
                                + baseline_rutgers + baseline_social_desirability + baseline_impulsivity + lifestress 
                                + injunctive_workplace_norms + qualitative_role_overload + quantitative_role_overload + DASS + DASS:injunctive_workplace_norms + time:DASS + time:DASS:injunctive_workplace_norms, 
                  data = dat_analysis, id = ParticipantID, waves = time, corstr = "exchangeable", family = "poisson")

outfit_rutgers_1 <- FormatGEEOutput(fit_rutgers_1)
N_rutgers_1 <- length(setdiff(unique(dat_analysis$ParticipantID), fit_rutgers_1$dropped))
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
outfit_rutgers_1 %>%
  mutate(parameter = gsub("_"," ", .data[["parameter"]])) %>%
  mutate(parameter = gsub(":"," x ", .data[["parameter"]])) %>%
  select(parameter, everything()) %>%
  mutate_all(linebreak) %>%
  kable(booktabs = TRUE, align = c('c','c','c','c'),
        col.names = linebreak(c("Parameter","Estimates","SE","p-value"), align = "c"),
        caption = paste("Outcome: RAPI; N = ", N_rutgers_1, "; QIC = ", round(QIC(fit_rutgers_1), digits = 2), sep=""), escape = FALSE) %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))  
```

\newpage

## HED

```{r, echo = FALSE, message = FALSE, warning = FALSE}
fit_HED_1 <- geem(HED ~ sex + race + age 
                                + baseline_HED + baseline_social_desirability + baseline_impulsivity + lifestress 
                                + injunctive_workplace_norms + qualitative_role_overload + quantitative_role_overload + DASS + DASS:injunctive_workplace_norms + time:DASS + time:DASS:injunctive_workplace_norms, 
                  data = dat_analysis, id = ParticipantID, waves = time, corstr = "exchangeable", family = "poisson")

outfit_HED_1 <- FormatGEEOutput(fit_HED_1)
N_HED_1 <- length(setdiff(unique(dat_analysis$ParticipantID), fit_HED_1$dropped))
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
outfit_HED_1 %>%
  mutate(parameter = gsub("_"," ", .data[["parameter"]])) %>%
  mutate(parameter = gsub(":"," x ", .data[["parameter"]])) %>%
  select(parameter, everything()) %>%
  mutate_all(linebreak) %>%
  kable(booktabs = TRUE, align = c('c','c','c','c'),
        col.names = linebreak(c("Parameter","Estimates","SE","p-value"), align = "c"),
        caption = paste("Outcome: Number of past-month heavy drinking days (HED); N = ", N_HED_1, "; QIC = ", round(QIC(fit_HED_1), digits = 2), sep=""), escape = FALSE) %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))  
```
