---
title: "Display correlation among variables"
author: 
date: '`r format(Sys.Date(), "%B %d, %Y")`'
geometry: margin=1in, paperheight=13.0in,paperwidth=8.5in, landscape
output: 
  pdf_document:
    number_sections: TRUE
---


```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(rmarkdown)
library(knitr)
library(kableExtra)
```

```{r global_options, include=FALSE}
knitr::opts_chunk$set(tidy = TRUE)
knitr::opts_chunk$set(fig.pos = 'H')
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(dplyr)
path_output_data <- Sys.getenv("path_output_data")
source("analysis-utils.R")

# Read in variable description
dat_baseline_vars <- read.csv(file.path(path_output_data, "dat_baseline_vars.csv"), header = TRUE)
dat_screener_vars <- read.csv(file.path(path_output_data, "dat_screener_vars.csv"), header = TRUE)
dat_wnw_vars <- read.csv(file.path(path_output_data, "dat_wnw_vars.csv"), header = TRUE)

# Read in data
dat_baseline_analysis <- read.csv(file.path(path_output_data, "dat_baseline_analysis.csv"), header = TRUE)
dat_screener_analysis <- read.csv(file.path(path_output_data, "dat_screener_analysis.csv"), header = TRUE)
dat_wnw_analysis <- read.csv(file.path(path_output_data, "dat_wnw_analysis.csv"), header = TRUE)
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
dat_wnw_0 <- dat_wnw_analysis[dat_wnw_analysis$time==0,dat_wnw_vars$new_var_name]
dat_wnw_1 <- dat_wnw_analysis[dat_wnw_analysis$time==1,dat_wnw_vars$new_var_name]

colnames(dat_wnw_0) <- paste(colnames(dat_wnw_0), "_time_0", sep="")
colnames(dat_wnw_1) <- paste(colnames(dat_wnw_1), "_time_1", sep="")

dat_corr <- cbind(dat_screener_analysis[,dat_screener_vars$new_var_name],
                  dat_baseline_analysis[,dat_baseline_vars$new_var_name],
                  dat_wnw_0,
                  dat_wnw_1)
cormat <- cor(dat_corr, use = "pairwise.complete.obs")
cormat <- round(cormat, digits=2)
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
row.names(cormat) <- NULL
cormat <- cbind(as.matrix(1:ncol(cormat)), cormat)
colnames(cormat) <- c("", 1:(ncol(cormat)-1))

kable(cormat, booktabs=TRUE) %>%
  column_spec(1, border_left = FALSE, border_right = TRUE) %>%
  kable_styling(position = "center")
```

\newpage


```{r, echo = FALSE, message = FALSE, warning = FALSE}
names_screener <- colnames(dat_screener_analysis[,dat_screener_vars$new_var_name])
names_baseline <- colnames(dat_baseline_analysis[,dat_baseline_vars$new_var_name])
names_wnw_0 <- colnames(dat_wnw_0)
names_wnw_1 <- colnames(dat_wnw_1)
names_allvars <- c(names_screener, names_baseline, names_wnw_0, names_wnw_1)

dat_varnames <- data.frame(Label = 1:length(names_allvars),
                           Variable = names_allvars)

dat_varnames$Variable <- c("Baseline HED", 
                           "Baseline RAPI",
                           "Sex", "Race", "Age", 
                           "Baseline social desirability", 
                           "Baseline impulsivity",
                           "Time 0: Life stress",
                           "Time 0: HED",
                           "Time 0: RAPI",
                           "Time 0: Qualitative role overload",
                           "Time 0: Quantitative role overload",
                           "Time 0: Injunctive norms",
                           "Time 0: Descriptive norms",
                           "Time 0: DASS",
                           "Time 1: Life stress",
                           "Time 1: HED",
                           "Time 1: RAPI",
                           "Time 1: Qualitative role overload",
                           "Time 1: Quantitative role overload",
                           "Time 1: Injunctive norms",
                           "Time 1: Descriptive norms",
                           "Time 1: DASS")
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
kable(dat_varnames, booktabs=TRUE, caption = "Note that when RAPI at time 0 and 1 were used to calculate specific values within the correlation matrix, calculation of correlation was restricted to only those participants who reported (within the same survey) to have no drinking in the past month") %>%
  row_spec(c(7,15), hline_after = TRUE) %>%
  kable_styling(position = "center")
```



```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(Hmisc)
dat_pval <- rcorr(x = as.matrix(dat_corr), type = "pearson")[["P"]]
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
for(j in 2:ncol(cormat)){
  dat_cordisplay <- data.frame(r = cormat[,j], p = dat_pval[,j-1])
  dat_cordisplay <-  dat_cordisplay %>%
    mutate(r_annotated = case_when(
      p <= 0.10 & p > 0.05 ~ paste(r, "\206", sep=""),
      p <= 0.05 & p > 0.01 ~ paste(r, "*", sep=""),
      p <= 0.01 & p > 0.001 ~ paste(r, "**", sep=""),
      p <= 0.001 ~ paste(r, "***", sep=""),
      TRUE ~ as.character(r)
    ))
  cormat[,j] <- dat_cordisplay[["r_annotated"]]
}
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
out_corr_table <- as.data.frame(cbind(dat_varnames$Variable, cormat[,2:ncol(cormat)]))
colnames(out_corr_table) <- c("variable", paste(1:(ncol(out_corr_table)-1)))
write.csv(out_corr_table, "explore-dataset/out_corr_table.csv", row.names = FALSE)
```
