---
title: "Hypothesis 3"
author: 
date: '`r format(Sys.Date(), "%B %d, %Y")`'
geometry: margin=0.7in
output: 
  pdf_document:
  number_sections: TRUE
---
  
  
```{r global_options, include=FALSE}
knitr::opts_chunk$set(tidy = TRUE)
knitr::opts_chunk$set(fig.pos = 'H')
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(rmarkdown)
library(knitr)
library(kableExtra)
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(dplyr)
library(geeM)
library(MuMIn)
path_output_data <- Sys.getenv("path_output_data")

# Read in functions for data analysis
source("analysis-utils.R")

# Read in data
dat_baseline_analysis <- read.csv(file.path(path_output_data, "dat_baseline_analysis.csv"), header = TRUE)
dat_screener_analysis <- read.csv(file.path(path_output_data, "dat_screener_analysis.csv"), header = TRUE)
dat_wnw_analysis <- read.csv(file.path(path_output_data, "dat_wnw_analysis.csv"), header = TRUE)

# Center and scale variables
dat_baseline_analysis <- dat_baseline_analysis %>% mutate(across(!c("ParticipantID"), scale))
dat_screener_analysis <- dat_screener_analysis %>% mutate(across(!c("ParticipantID","sex","race","baseline_condition"), scale))
dat_wnw_analysis_0 <- dat_wnw_analysis %>% filter(time==0) %>% mutate(across(!c("ParticipantID","time","survey_timepoint","CASEID","HED","rutgers","condition"), scale))
dat_wnw_analysis_1 <- dat_wnw_analysis %>% filter(time==1) %>% mutate(across(!c("ParticipantID","time","survey_timepoint","CASEID","HED","rutgers","condition"), scale))
dat_wnw_analysis <- rbind(dat_wnw_analysis_0, dat_wnw_analysis_1)
remove(dat_wnw_analysis_0, dat_wnw_analysis_1)

# Merge datasets into one data frame
dat_wnw_analysis <- dat_wnw_analysis %>% arrange(ParticipantID, time)
dat_analysis <- left_join(x = dat_wnw_analysis, y = dat_screener_analysis, by = "ParticipantID")
dat_analysis <- left_join(x = dat_analysis, y = dat_baseline_analysis, by = "ParticipantID")
dat_analysis <- dat_analysis %>% select(colnames(dat_screener_analysis), colnames(dat_baseline_analysis), everything())
```

(H3) The effect of drinking norms on alcohol misuse intensifies over time: It is stronger during the late onboarding phase than the early onboarding phase

# Model 4

## RAPI


```{r, echo = FALSE, message = FALSE, warning = FALSE}
fit_rutgers_3 <- geem(rutgers ~ sex + race + age 
                                + baseline_rutgers + baseline_social_desirability + baseline_impulsivity + lifestress
                                + injunctive_workplace_norms + qualitative_role_overload + quantitative_role_overload
                                + time
                                + time:injunctive_workplace_norms + time:qualitative_role_overload + time:quantitative_role_overload, 
                  data = dat_analysis, id = ParticipantID, waves = time, corstr = "exchangeable", family = "poisson")

outfit_rutgers_3 <- FormatGEEOutput(fit_rutgers_3)
N_rutgers_3 <- length(setdiff(unique(dat_analysis$ParticipantID), fit_rutgers_3$dropped))
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
Lmat <- matrix(c(0,0,0,0,0,0,0,0,
                 0, # Norms at time 0
                 1, # Qualitative Overload at time=0
                 0, # Quantitative Overload at time=0
                 0,0,0,0),
               byrow=TRUE, nrow=1)
Lmat_labels <- c("Qualitative Role Overload (time=0)")
qualitative_role_overload_0 <- GetSS(use_this_model = fit_rutgers_3, L = Lmat, contrast_labels = Lmat_labels)

Lmat <- matrix(c(0,0,0,0,0,0,0,0,
                 0, # Norms at time 0
                 0, # Qualitative Overload at time=0
                 1, # Quantitative Overload at time=0
                 0,0,0,0),
               byrow=TRUE, nrow=1)
Lmat_labels <- c("Quantitative Role Overload (time=0)")
quantitative_role_overload_0 <- GetSS(use_this_model = fit_rutgers_3, L = Lmat, contrast_labels = Lmat_labels)

Lmat <- matrix(c(0,0,0,0,0,0,0,0,
                 1, # Norms at time 0
                 0, # Qualitative Overload at time=0
                 0, # Quantitative Overload at time=0
                 0,0,0,0),
               byrow=TRUE, nrow=1)
Lmat_labels <- c("Norms (time=0)")
norms_0 <- GetSS(use_this_model = fit_rutgers_3, L = Lmat, contrast_labels = Lmat_labels)

Lmat <- matrix(c(0,0,0,0,0,0,0,0,
                 0, # Norms at time 0
                 1, # Qualitative Overload at time=0
                 0, # Quantitative Overload at time=0
                 0, # Time
                 0, # Time x norms
                 1, # Time x qualitative role overload
                 0  # Time x quantitative role overload
                 ),
               byrow=TRUE, nrow=1)
Lmat_labels <- c("Qualitative Role Overload (time=1)")
qualitative_role_overload_1 <- GetSS(use_this_model = fit_rutgers_3, L = Lmat, contrast_labels = Lmat_labels)

Lmat <- matrix(c(0,0,0,0,0,0,0,0,
                 0, # Norms at time 0
                 0, # Qualitative Overload at time=0
                 1, # Quantitative Overload at time=0
                 0, # Time
                 0, # Time x norms
                 1, # Time x qualitative role overload
                 1  # Time x quantitative role overload
                 ),
               byrow=TRUE, nrow=1)
Lmat_labels <- c("Quantitative Role Overload (time=1)")
quantitative_role_overload_1 <- GetSS(use_this_model = fit_rutgers_3, L = Lmat, contrast_labels = Lmat_labels)

Lmat <- matrix(c(0,0,0,0,0,0,0,0,
                 1, # Norms at time 0
                 0, # Qualitative Overload at time=0
                 0, # Quantitative Overload at time=0
                 0, # Time
                 1, # Time x norms
                 0, # Time x qualitative role overload
                 0  # Time x quantitative role overload
                 ),
               byrow=TRUE, nrow=1)
Lmat_labels <- c("Norms (time=1)")
norms_1 <- GetSS(use_this_model = fit_rutgers_3, L = Lmat, contrast_labels = Lmat_labels)

dat_all_ss <- rbind(qualitative_role_overload_0,
                    quantitative_role_overload_0,
                    norms_0,
                    qualitative_role_overload_1,
                    quantitative_role_overload_1,
                    norms_1)

ss_fit_rutgers_3 <- dat_all_ss
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
write.csv(outfit_rutgers_3, "prepare-publication-tables/RAPI/injunctive_model_04.csv", row.names=FALSE)
write.csv(ss_fit_rutgers_3, "prepare-publication-tables/RAPI/injunctive_ss_model_04.csv", row.names=FALSE)
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
outfit_rutgers_3 %>%
  mutate(parameter = gsub("_"," ", .data[["parameter"]])) %>%
  mutate(parameter = gsub(":"," x ", .data[["parameter"]])) %>%
  select(parameter, everything()) %>%
  mutate_all(linebreak) %>%
  kable(booktabs = TRUE, align = c('c','c','c','c'),
        col.names = linebreak(c("Parameter","Estimates","SE","p-value"), align = "c"),
        caption = paste("Outcome: Rutgers Alcohol Problem Index; N = ", N_rutgers_3,   "; QIC = ", round(QIC(fit_rutgers_3), digits = 2), sep=""), escape = FALSE) %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))  

ss_fit_rutgers_3 %>%
  kable(booktabs = TRUE, 
        col.names = c("Parameter","Estimates","SE","p-value")) %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))
```

\newpage

## HED


```{r, echo = FALSE, message = FALSE, warning = FALSE}
fit_HED_3 <- geem(HED ~ sex + race + age 
                                + baseline_HED + baseline_social_desirability + baseline_impulsivity + lifestress
                                + injunctive_workplace_norms + qualitative_role_overload + quantitative_role_overload
                                + time
                                + time:injunctive_workplace_norms + time:qualitative_role_overload + time:quantitative_role_overload, 
                  data = dat_analysis, id = ParticipantID, waves = time, corstr = "exchangeable", family = "poisson")

outfit_HED_3 <- FormatGEEOutput(fit_HED_3)
N_HED_3 <- length(setdiff(unique(dat_analysis$ParticipantID), fit_HED_3$dropped))
```



```{r, echo = FALSE, message = FALSE, warning = FALSE}
Lmat <- matrix(c(0,0,0,0,0,0,0,0,
                 0, # Norms at time 0
                 1, # Qualitative Overload at time=0
                 0, # Quantitative Overload at time=0
                 0,0,0,0),
               byrow=TRUE, nrow=1)
Lmat_labels <- c("Qualitative Role Overload (time=0)")
qualitative_role_overload_0 <- GetSS(use_this_model = fit_HED_3, L = Lmat, contrast_labels = Lmat_labels)

Lmat <- matrix(c(0,0,0,0,0,0,0,0,
                 0, # Norms at time 0
                 0, # Qualitative Overload at time=0
                 1, # Quantitative Overload at time=0
                 0,0,0,0),
               byrow=TRUE, nrow=1)
Lmat_labels <- c("Quantitative Role Overload (time=0)")
quantitative_role_overload_0 <- GetSS(use_this_model = fit_HED_3, L = Lmat, contrast_labels = Lmat_labels)

Lmat <- matrix(c(0,0,0,0,0,0,0,0,
                 1, # Norms at time 0
                 0, # Qualitative Overload at time=0
                 0, # Quantitative Overload at time=0
                 0,0,0,0),
               byrow=TRUE, nrow=1)
Lmat_labels <- c("Norms (time=0)")
norms_0 <- GetSS(use_this_model = fit_HED_3, L = Lmat, contrast_labels = Lmat_labels)

Lmat <- matrix(c(0,0,0,0,0,0,0,0,
                 0, # Norms at time 0
                 1, # Qualitative Overload at time=0
                 0, # Quantitative Overload at time=0
                 0, # Time
                 0, # Time x norms
                 1, # Time x qualitative role overload
                 0  # Time x quantitative role overload
                 ),
               byrow=TRUE, nrow=1)
Lmat_labels <- c("Qualitative Role Overload (time=1)")
qualitative_role_overload_1 <- GetSS(use_this_model = fit_HED_3, L = Lmat, contrast_labels = Lmat_labels)

Lmat <- matrix(c(0,0,0,0,0,0,0,0,
                 0, # Norms at time 0
                 0, # Qualitative Overload at time=0
                 1, # Quantitative Overload at time=0
                 0, # Time
                 0, # Time x norms
                 1, # Time x qualitative role overload
                 1  # Time x quantitative role overload
                 ),
               byrow=TRUE, nrow=1)
Lmat_labels <- c("Quantitative Role Overload (time=1)")
quantitative_role_overload_1 <- GetSS(use_this_model = fit_HED_3, L = Lmat, contrast_labels = Lmat_labels)

Lmat <- matrix(c(0,0,0,0,0,0,0,0,
                 1, # Norms at time 0
                 0, # Qualitative Overload at time=0
                 0, # Quantitative Overload at time=0
                 0, # Time
                 1, # Time x norms
                 0, # Time x qualitative role overload
                 0  # Time x quantitative role overload
                 ),
               byrow=TRUE, nrow=1)
Lmat_labels <- c("Norms (time=1)")
norms_1 <- GetSS(use_this_model = fit_HED_3, L = Lmat, contrast_labels = Lmat_labels)

dat_all_ss <- rbind(qualitative_role_overload_0,
                    quantitative_role_overload_0,
                    norms_0,
                    qualitative_role_overload_1,
                    quantitative_role_overload_1,
                    norms_1)

ss_fit_HED_3 <- dat_all_ss
```




```{r, echo = FALSE, message = FALSE, warning = FALSE}
outfit_HED_3 %>%
  mutate(parameter = gsub("_"," ", .data[["parameter"]])) %>%
  mutate(parameter = gsub(":"," x ", .data[["parameter"]])) %>%
  select(parameter, everything()) %>%
  mutate_all(linebreak) %>%
  kable(booktabs = TRUE, align = c('c','c','c','c'),
        col.names = linebreak(c("Parameter","Estimates","SE","p-value"), align = "c"),
        caption = paste("Outcome: Number of past-month heavy drinking days (HED); N = ", N_HED_3,   "; QIC = ", round(QIC(fit_HED_3), digits = 2), sep=""), escape = FALSE) %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))  

ss_fit_HED_3 %>%
  kable(booktabs = TRUE, 
        col.names = c("Parameter","Estimates","SE","p-value")) %>%
  kable_styling(full_width = FALSE, latex_options = c("HOLD_position"))
```


```{r, echo = FALSE, message = FALSE, warning = FALSE}
write.csv(outfit_HED_3, "prepare-publication-tables/HED/injunctive_model_04.csv", row.names=FALSE)
write.csv(ss_fit_HED_3, "prepare-publication-tables/HED/injunctive_ss_model_04.csv", row.names=FALSE)
```






